//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProgram_MOD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PeopleID
    {
        public int ID { get; set; }
        public int PeopleID1 { get; set; }
        public System.Guid PeopleCode { get; set; }
        public System.DateTimeOffset RegDate { get; set; }
    
        public virtual People People { get; set; }
    }
}
