//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProgram_MOD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_GetAllDataFromDatabase
    {
        public int ID { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public System.DateTime BornDate { get; set; }
        public Nullable<System.Guid> PeopleCode { get; set; }
        public Nullable<System.DateTimeOffset> RegDate { get; set; }
    }
}
